FROM ursa/frepple-6:latest
MAINTAINER Open Source Integrators <support@opensourceintegrators.com>

# For FrePPLe enterprise
# COPY ubuntu18-frepple-6.11.0.deb /frepple/ubuntu18-frepple-6.11.0.deb
# RUN apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y \
#  --no-install-recommends /frepple/ubuntu18-frepple-6.11.0.deb
# COPY license.xml /etc/frepple/license.xml
# Configure Apache
# RUN a2enmod proxy && a2enmod proxy_wstunnel    # Only Enterprise Edition
