FROM ursa/frepple-6:latest
MAINTAINER Open Source Integrators <support@opensourceintegrators.com>

# For FrePPLe enterprise
# ENV VERSION=6.22.0
# Download the package from https://frepple.com/customer-portal/downloads/
# COPY ubuntu18-frepple-$VERSION.deb /frepple/frepple.deb
# RUN apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y \
#  --no-install-recommends /frepple/frepple.deb && rm -f /frepple/frepple.deb
# COPY license.xml /etc/frepple/license.xml

# Customizations
# COPY custom /usr/lib/python3/dist-packages/freppledb/

# Configure Apache
# RUN a2enmod proxy && a2enmod proxy_wstunnel    # Only Enterprise Edition
