version: '2'
services:
  db:
    image: ursa/postgresql-13.0:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=frepple
      - POSTGRES_PASSWORD=frepple
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'

  app:
    build: ./frepple
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=frepple
      - PGPASSWORD=frepple
      - PGDATABASE=frepple
      - FREPPLE_ADMIN_NAME="Open Source Integrators"
      - FREPPLE_ADMIN_EMAIL="support@opensourceintegrators.com"
      - FREPPLE_INSTALLED_APPS_FORECASTING=true
      - FREPPLE_INSTALLED_APPS_INVENTORY=true
      - FREPPLE_INSTALLED_APPS_ODOO=true

volumes:
  postgres-data:
