apiVersion: v1
name: frepple
version: 6.11
appVersion: 6.11
description: FrePPLe instance.
home: https://github.com/ursais/frepple-template
icon: https://github.com/opensourceintegrators.png
keywords:
- frepple
- mrp
- aps
- http
- web
sources:
- https://github.com/ursais/frepple-template
maintainers:
- name: Open Source Integrators
  email: support@opensourceintegrators.com
engine: gotpl
