{{- if eq .Values.environment "production" }}
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: {{ print .Values.name "-backup" | quote }}
  annotations:
    description: Backup the production database and filestore everyday
spec:
  schedule: '50 6 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      template:
        metadata:
          labels:
            parent: {{ print .Values.name "-backup" | quote }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ print .Values.name "-backup" | quote }}
              image: ursa/backup:latest
              args:
                - backup
                - {{ print .Values.name }}
              env:
                - name: PGHOST
                  value: {{ ternary (include "app.postgresql.fullname" .) .Values.externalDatabase.host .Values.postgresql.enabled | quote }}
                - name: PGPORT
                  value: {{ ternary "5432" .Values.externalDatabase.port .Values.postgresql.enabled | quote }}
                - name: PGDATABASE
                  value: master
                - name: PGUSER
                  value: {{ ternary .Values.postgresql.postgresqlUsername .Values.externalDatabase.user .Values.postgresql.enabled | quote }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ ternary (include "app.postgresql.fullname" .) (printf "%s-%s" .Release.Name "externaldb") .Values.postgresql.enabled | quote }}
                      key: {{ ternary "postgresql-password" "db-password" .Values.postgresql.enabled | quote }}
                - name: PGDEFAULTDB
                  value: {{ ternary .Values.postgresql.defaultdb .Values.externalDatabase.defaultdb .Values.postgresql.enabled | quote }}
                - name: PGSSLMODE
                  value: {{ ternary .Values.postgresql.sslmode .Values.externalDatabase.sslmode .Values.postgresql.enabled | quote }}
                - name: RUNNING_ENV
                  value: {{ .Values.environment }}
                - name: PLATFORM
                  value: {{ .Values.platform }}
{{- end }}
---
{{- if or (eq .Values.environment "qa") (eq .Values.environment "test") }}
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: {{ print .Values.name "-restore" | quote }}
  annotations:
    description: Restore the production database and filestore every week in BACKUP
spec:
  schedule: '0 12 * * mon'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      template:
        metadata:
          labels:
            parent: {{ print .Values.name "-restore" | quote }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ print .Values.name "-restore" | quote }}
              image: ursa/backup:latest
              args:
                - restore
                - {{ print .Values.name }}
              env:
                - name: PGHOST
                  value: {{ ternary (include "app.postgresql.fullname" .) .Values.externalDatabase.host .Values.postgresql.enabled | quote }}
                - name: PGPORT
                  value: {{ ternary "5432" .Values.externalDatabase.port .Values.postgresql.enabled | quote }}
                - name: PGDATABASE
                  value: backup
                - name: PGUSER
                  value: {{ ternary .Values.postgresql.postgresqlUsername .Values.externalDatabase.user .Values.postgresql.enabled | quote }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ ternary (include "app.postgresql.fullname" .) (printf "%s-%s" .Release.Name "externaldb") .Values.postgresql.enabled | quote }}
                      key: {{ ternary "postgresql-password" "db-password" .Values.postgresql.enabled | quote }}
                - name: PGDEFAULTDB
                  value: {{ ternary .Values.postgresql.defaultdb .Values.externalDatabase.defaultdb .Values.postgresql.enabled | quote }}
                - name: PGSSLMODE
                  value: {{ ternary .Values.postgresql.sslmode .Values.externalDatabase.sslmode .Values.postgresql.enabled | quote }}
                - name: RUNNING_ENV
                  value: {{ .Values.environment }}
                - name: PLATFORM
                  value: {{ .Values.platform }}
{{- end }}
