apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Release.IsInstall }}
  odoo-password-default: {{ randAlphaNum 16 | b64enc | quote }}
  secret-key: {{ randAlphaNum 16 | b64enc | quote }}
  secret-webtoken-key: {{ randAlphaNum 16 | b64enc | quote }}
  {{ else }}
  odoo-password-default: {{ index (lookup "v1" "Secret" .Release.Namespace (include "app.fullname" . )).data "odoo-password-default" }}
  secret-key: {{ index (lookup "v1" "Secret" .Release.Namespace (include "app.fullname" . )).data "secret-key" }}
  secret-webtoken-key: {{ index (lookup "v1" "Secret" .Release.Namespace (include "app.fullname" . )).data "secret-webtoken-key" }}
  {{ end }}
---
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "externaldb"  }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Release.IsInstall }}
  db-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ else }}
  db-password: {{ index (lookup "v1" "Secret" .Release.Name (printf "%s-%s" .Release.Name "externaldb")).data "db-password" }}
  {{ end }}
{{- end }}
